pipeline {
    agent any

    environment {
        ROBOT_PATH = './tests'  // โฟลเดอร์เก็บไฟล์ Robot Framework
        RESULTS_PATH = './results'  // ที่เก็บผลลัพธ์การทดสอบ
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/xEXCEEDx/SwagLab-Test.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh 'pip install -r requirements.txt'
                    sh 'pip install robotframework robotframework-seleniumlibrary'
                }
            }
        }

        stage('Run Robot Tests') {
            steps {
                script {
                    sh 'robot --outputdir ${RESULTS_PATH} ${ROBOT_PATH}/*.robot'
                }
            }
        }

        stage('Publish Results') {
            steps {
                junit '**/results/output.xml'
                publishHTML(target: [
                    reportDir: 'results',
                    reportFiles: 'report.html',
                    reportName: 'Robot Test Report'
                ])
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo '✅ Test Passed!'
        }
        failure {
            echo '❌ Test Failed!'
        }
    }
}
