name: Auto Commit, Push, and Trigger Jenkins

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # รันทุก 10 นาที (สามารถแก้ได้)

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Auto Commit and Push
        run: |
          git add .
          git commit -m "Auto commit from GitHub Actions" || echo "No changes to commit"
          git push origin main

  trigger_jenkins:
    needs: auto_commit
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://your-jenkins-url/job/your-job-name/build?token=YOUR_JENKINS_TOKEN"
